### PR TITLE
fix: nil pointer dereference on UserInfoAddress

### LINKED ISSUE #203: `invalid memory address or nil pointer dereference` when accessing UserInfoAddress
**Describe the bug**
When user info is missing address field it's decoded into `userinfo` struct where `Address` field has `UserInfoAddress` type but `nil` value.

`UserInfoAddress` type doesn't expect `nil` as receiver, so code like `info.GetAddress().GetCountry()` panics.

**To Reproduce**
1. Unmarshal userinfo without address
2. Try `info.GetAddress().GetCountry()`
3. See panic

**Expected behavior**
Probably, returning default values for all fields (e.g. `""`).

Another (IMO better but breaking) way is to return a pointer. So it will be possible to check value `GetAddress() == nil`

**Additional context**
Temp workaround:
```go
func isNil(val any) bool {
	return val == nil || (reflect.ValueOf(val).Kind() == reflect.Ptr && reflect.ValueOf(val).IsNil())
}

addr := info.GetAddress()
if !isNil(addr) {
  // ...
}
```

### PR DESCRIPTION
**Pull request by muhlemmer**
When the Address field in userinfo is nil, an empty instance of userInfoAddress is now returned. This allows for safe chaining of Get methods. All of an empty userInfoAddress' Get methods will return empty strings.

Fixes #203

### CODE REVIEW

**Review by muir — APPROVED** [review]

**Comment by muhlemmer** [comment]
I've updated this PR to catch the nil in `userinfo.UnmarshalJSON` and set a new empty value to the `userinfo.Address` field. The original change in `userinfo.GetAddress()` is reverted. And the tests now use actual json.

File: pkg/oidc/userinfo.go [hunk 1]
```diff
@@ -389,7 +389,13 @@ func (u *userinfo) UnmarshalJSON(data []byte) error {
 	if err := json.Unmarshal(data, &a); err != nil {
 		return err
 	}
-	u.Address = a.Address
+
+	if a.Address == nil {
+		u.Address = new(userInfoAddress)
+	} else {
+		u.Address = a.Address
+	}
```
Comment (livio-a) [inline pkg/oidc/userinfo.go:397]: what about if we only check for nil here:
```go
if a.Address != nil {
	u.Address = a.Address
}
```
and an additional check in the GetAddress():
```go
func (u *userinfo) GetAddress() UserInfoAddress {
	if u.Address == nil {
		return &userInfoAddress{}
	}
	return u.Address
}
```
this way we can avoid the nil pointer and marshalling the userinfo again would return the same values as we had before unmarshalling

File: pkg/oidc/userinfo_test.go [hunk 2]
```diff
@@ -81,3 +81,35 @@ func TestUserInfoEmailVerifiedUnmarshal(t *testing.T) {
...
+	}
+
+	for _, tt := range tests {
+		t.Run(tt.name, func(t *testing.T) {
+			info := &userinfo{}
+			if err := json.Unmarshal([]byte(tt.data), info); err != nil {
+				t.Fatal(err)
+			}
+
+			info.GetAddress().GetCountry() //<- used to panic
```
Comment (livio-a) [inline pkg/oidc/userinfo_test.go:112]:
```suggestion
			err := json.Unmarshal([]byte(tt.data), info)
			assert.NoError(t, err)

			info.GetAddress().GetCountry() //<- used to panic

			// now shortly assure that a marshalling still produces the same as was parsed into the struct
			marshal, err := json.Marshal(info)
			assert.NoError(t, err)
			assert.Equal(t, tt.data, string(marshal))
```

**Review by livio-a — COMMENTED** [review]
hey @muhlemmer what do you think about this proposal?

File: pkg/oidc/userinfo.go (hunk 1 above)
Comment (muhlemmer) [reply pkg/oidc/userinfo.go]: I agree. Done

**Comment by muhlemmer** [comment]
@livio-a  I've rebased, because the test were failing with my old branch. Comments are resolved.

**Review by livio-a — APPROVED** [review]
